logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: DEBUG
    io.devandre.furtmates: DEBUG

spring:
  application:
    name: Synthdrive Backend
  threads:
    virtual:
      enabled: true
  datasource:
    hikari:
      poolName: Hikari
      auto-commit: false
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          batch_size: 25
        query:
          fail_on_pagination_over_collection_fetch: true
          in_clause_parameter_padding: true
        generate_statistics: false
        order_updates: true
        connection:
          provider_disables_autocommit: true
        order_inserts: true
        default_schema: synthdrive_schema
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true
  liquibase:
    change-log: classpath:db/changelog/master.xml
    default-schema: synthdrive_schema
    contexts: dev
  #    drop-first: true

  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8080

secret:
  app:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: ${JWT_EXPIRATION_MS}

frontend:
  url: ${FRONTEND_URL}

#application:
#  stripe:
#    api-key: ${STRIPE_API_KEY}
#    webhook-secret: ${STRIPE_WEBHOOK_SECRET}